name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linter
      run: npm run lint

    - name: Run type check
      run: npm run typecheck

    - name: Run tests
      run: npm run test

    - name: Build project
      run: npm run build

  # Skip deployment for docs-only changes
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      docs-only: ${{ steps.changes.outputs.docs-only }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Check for docs-only changes
      id: changes
      run: |
        if [[ $(git diff --name-only HEAD~1 HEAD | grep -v -E '\.(md|txt)$' | wc -l) -eq 0 ]]; then
          echo "docs-only=true" >> $GITHUB_OUTPUT
        else
          echo "docs-only=false" >> $GITHUB_OUTPUT
        fi
